name: flutter_embed_unity_ios_example
description: Demonstrates how to use the flutter_embed_unity_android plugin.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

environment:
  sdk: '>=3.0.6 <4.0.0'
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_embed_unity_ios:
    # When depending on this package from a real application you should use:
    #   flutter_embed_unity_ios: ^x.y.z
    # See https://dart.dev/tools/pub/dependencies#version-constraints
    # The example app is bundled with the plugin so we use a path dependency on
    # the parent directory to use the current plugin's version.
    path: ../
  flutter_embed_unity:
    path: ../../flutter_embed_unity
  intl: any


dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.3


flutter:
  uses-material-design: true
