name: flutter_embed_unity_2022_3_ios
description: iOS implementation for Unity 2022.3 LTS of the flutter_embed_unity plugin.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 0.0.1

environment:
  sdk: '>=3.0.6 <4.0.0'
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_embed_unity_platform_interface: #^0.0.1
    path: ../flutter_embed_unity_platform_interface

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
 plugin:
    implements: flutter_embed_unity
    platforms:
      ios:
        package: com.learntoflutter.flutter_embed_unity_ios
        pluginClass: FlutterEmbedUnityIosPlugin