name: flutter_embed_unity
description: Harness the power of Unity 3D in your Flutter app by embedding Unity as a widget. Useful for adding 3D, gaming or augmented reality (AR) to your app.
version: 0.0.1
homepage: https://learntoflutter.com
repository: https://github.com/learntoflutter/flutter_embed_unity
documentation: https://github.com/learntoflutter/flutter_embed_unity/wiki
funding:
  - https://www.buymeacoffee.com/pPDtNs6A6T
topics:
  - unity
  - 3D
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

environment:
  sdk: '>=3.0.6 <4.0.0'
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  # The design on https://flutter.dev/go/federated-plugins was to leave
  # this constraint as "any". We cannot do it right now as it fails pub publish
  # validation, so we set a ^ constraint.
  # TODO: Revisit this (either update this part in the design or the pub tool).
  # https://github.com/flutter/flutter/issues/46264
  flutter_embed_unity_platform_interface: #^0.0.1
    path: ../flutter_embed_unity_platform_interface
  flutter_embed_unity_2022_3_android: #^0.0.1
    path: ../flutter_embed_unity_2022_3_android
  flutter_embed_unity_2022_3_ios: #^0.0.1
    path: ../flutter_embed_unity_2022_3_ios

dev_dependencies:
  flutter_lints: ^2.0.3

flutter:
  plugin:
    platforms:
      android:
        default_package: flutter_embed_unity_2022_3_android
      ios:
        default_package: flutter_embed_unity_2022_3_ios
